version: "3.9"

services:
  rails_app:
    build: .
    command: rails s -b 0.0.0.0
    volumes:
      - .:/usr/src
    ports:      
      - "3000:3000"
    depends_on:
    - redis
    environment:
      REDIS_URL: redis://redis:6379/0

  sinatra_server:
    build: hw4.1/
    command: ruby ./lib/sinatra_server.rb
    ports:
      - 5678:5678
  
  sidekiq:
    build: .
    command: sidekiq
    volumes:
      - ./:/usr/src/
    environment:
      REDIS_URL: redis://redis:6379/0

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 15672:15672
    volumes:
      - rabbit:/var/lib/rabbitmq

  redis:
    image: redis:alpine
    volumes:
      - redis:/data


volumes:
  rabbit:
  redis: