version: "3.9"

services:
  rails_app:
    build: .
    command: rails s -b 0.0.0.0
    volumes:
      - .:/usr/src
    ports:      
      - "3000:3000"

  sinatra_server:
    build: hw4/
    command: ruby ./lib/sinatra_server.rb
    ports:
      - 5678:5678
    